### ISSUE TITLE
application stuck at "optimizing application"

### ISSUE THREAD

**Issue by bjo81** [luminoso/fedora-copr-signal-desktop#11]
After the last ugprade, the app is stuck at "optimizing application". vips was installed after reading #9 

```
NODE_CONFIG_DIR /usr/lib64/signal-desktop/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/xyz/.config/Signal
config/get: Did not find user config file, cache is now empty object
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
x-attr dependency did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
key/initialize: Generating new encryption key, since we did not find it on disk
config/set: Saving user config to disk
{"level":30,"time":"2021-08-31T09:08:09.308Z","pid":86814,"hostname":"some.host","msg":"app ready"}
{"level":30,"time":"2021-08-31T09:08:09.308Z","pid":86814,"hostname":"some.host","msg":"starting version 5.15.0"}
{"level":30,"time":"2021-08-31T09:08:09.309Z","pid":86814,"hostname":"some.host","msg":"media access status"}
migrateSchemaVersion: Migrating from schema_version 0 to user_version 0
updateSchema:
  Current user_version: 0;
  Most recent db schema: 39;
  SQLite version: 3.34.1;
  SQLCipher version: 4.4.3 community;
  (deprecated) schema_version: 0;

updateToSchemaVersion1: starting...
updateToSchemaVersion1: success!
updateToSchemaVersion2: starting...
updateToSchemaVersion2: success!
updateToSchemaVersion3: starting...
updateToSchemaVersion3: success!
updateToSchemaVersion4: starting...
updateToSchemaVersion4: success!
updateToSchemaVersion6: starting...
updateToSchemaVersion6: success!
updateToSchemaVersion7: starting...
updateToSchemaVersion7: success!
updateToSchemaVersion8: starting...
updateToSchemaVersion8: success!
updateToSchemaVersion9: starting...
updateToSchemaVersion9: success!
updateToSchemaVersion10: starting...
updateToSchemaVersion10: success!
updateToSchemaVersion11: starting...
updateToSchemaVersion11: success!
updateToSchemaVersion12: starting...
updateToSchemaVersion12: success!
updateToSchemaVersion13: starting...
updateToSchemaVersion13: success!
updateToSchemaVersion14: starting...
updateToSchemaVersion14: success!
updateToSchemaVersion15: starting...
updateToSchemaVersion15: success!
updateToSchemaVersion16: starting...
updateToSchemaVersion16: success!
updateToSchemaVersion17: starting...
updateToSchemaVersion17: Index messages_view_once did not already exist
updateToSchemaVersion17: success!
updateToSchemaVersion18: starting...
updateToSchemaVersion18: success!
updateToSchemaVersion19: starting...
updateToSchemaVersion19: success!
updateToSchemaVersion20: starting...
updateToSchemaVersion20: success!
updateToSchemaVersion21: success!
updateToSchemaVersion22: success!
updateToSchemaVersion23: success!
updateToSchemaVersion24: success!
updateToSchemaVersion25: success!
updateToSchemaVersion26: success!
updateToSchemaVersion27: success!
updateToSchemaVersion28: success!
updateToSchemaVersion29: success!
updateToSchemaVersion30: success!
updateToSchemaVersion31: starting...
updateToSchemaVersion31: success!
updateToSchemaVersion32: success!
updateToSchemaVersion33: success!
updateToSchemaVersion34: success!
updateToSchemaVersion35: success!
updateToSchemaVersion36: success!
updateToSchemaVersion37: success!
updateToSchemaVersion38: success!
updateToSchemaVersion39: success!
{"level":30,"time":"2021-08-31T09:08:11.320Z","pid":86814,"hostname":"some.host","msg":"config/set: Saving ephemeral config to disk"}
{"level":30,"time":"2021-08-31T09:08:11.322Z","pid":86814,"hostname":"some.host","msg":"got slow spellcheck setting true"}
{"level":30,"time":"2021-08-31T09:08:11.322Z","pid":86814,"hostname":"some.host","msg":"getSystemTraySetting had no flags and did no DB lookups. Returning DoNotUseSystemTray"}
{"level":30,"time":"2021-08-31T09:08:11.323Z","pid":86814,"hostname":"some.host","msg":"Location reset needed"}
{"level":30,"time":"2021-08-31T09:08:11.323Z","pid":86814,"hostname":"some.host","msg":"Initializing BrowserWindow config: {\"show\":false,\"width\":800,\"height\":610,\"minWidth\":680,\"minHeight\":550,\"autoHideMenuBar\":false,\"titleBarStyle\":\"default\",\"backgroundColor\":\"#3a76f0\",\"webPreferences\":{\"devTools\":false,\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"contextIsolation\":false,\"enableRemoteModule\":true,\"preload\":\"/usr/lib64/signal-desktop/resources/app.asar/preload.bundle.js\",\"nativeWindowOpen\":true,\"spellcheck\":true,\"backgroundThrottling\":false},\"icon\":\"/usr/lib64/signal-desktop/resources/app.asar/images/signal-logo-desktop-linux.png\"}"}
{"level":30,"time":"2021-08-31T09:08:11.374Z","pid":86814,"hostname":"some.host","msg":"spellcheck: user locale: de-DE"}
{"level":30,"time":"2021-08-31T09:08:11.374Z","pid":86814,"hostname":"some.host","msg":"spellcheck: available spellchecker languages:  [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2021-08-31T09:08:11.374Z","pid":86814,"hostname":"some.host","msg":"spellcheck: setting languages to:  [\"de-DE\",\"de\"]"}
{"level":30,"time":"2021-08-31T09:08:11.392Z","pid":86814,"hostname":"some.host","msg":"got fast spellcheck setting true"}
{"level":30,"time":"2021-08-31T09:08:11.434Z","pid":86814,"hostname":"some.host","msg":"System tray service: created"}
{"level":30,"time":"2021-08-31T09:08:11.435Z","pid":86814,"hostname":"some.host","msg":"System tray service: updating main window. Previously, there was not a window, and now there is"}
{"level":30,"time":"2021-08-31T09:08:11.435Z","pid":86814,"hostname":"some.host","msg":"System tray service: rendering no tray"}
{"level":30,"time":"2021-08-31T09:08:11.435Z","pid":86814,"hostname":"some.host","msg":"Begin ensuring permissions"}
{"level":30,"time":"2021-08-31T09:08:11.460Z","pid":86814,"hostname":"some.host","msg":"Ensuring file permissions for 4 files"}
{"level":30,"time":"2021-08-31T09:08:11.462Z","pid":86814,"hostname":"some.host","msg":"Finish ensuring permissions in 27ms"}
{"level":30,"time":"2021-08-31T09:08:13.889Z","pid":86814,"hostname":"some.host","msg":"sending `database-ready`"}
{"level":30,"time":"2021-08-31T09:08:13.894Z","pid":86814,"hostname":"some.host","msg":"main window is ready-to-show"}
{"level":30,"time":"2021-08-31T09:08:13.894Z","pid":86814,"hostname":"some.host","msg":"showing main window"}
{"level":30,"time":"2021-08-31T09:08:13.911Z","pid":86814,"hostname":"some.host","msg":"System tray service: rendering no tray"}
{"level":30,"time":"2021-08-31T09:08:14.423Z","pid":86814,"hostname":"some.host","msg":"Updating BrowserWindow config: {\"maximized\":false,\"autoHideMenuBar\":false,\"fullscreen\":false,\"width\":800,\"height\":610,\"x\":562,\"y\":266}"}
{"level":30,"time":"2021-08-31T09:08:14.423Z","pid":86814,"hostname":"some.host","msg":"config/set: Saving ephemeral config to disk"}
```
```
{"level":30,"time":"2021-08-31T09:08:13.740Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"x-attr dependency did not load successfully"}
{"level":30,"time":"2021-08-31T09:08:13.755Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"preload complete"}
{"level":30,"time":"2021-08-31T09:08:13.888Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"Initializing SQL in renderer"}
{"level":30,"time":"2021-08-31T09:08:14.002Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"migrateDatabase: Migration without cipher change failed"}
{"level":50,"time":"2021-08-31T09:08:14.017Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"Database startup error: SqliteError: file is not a database\n    at Database.pragma ([REDACTED]/resources/app.asar/node_modules/better-sqlite3/lib/methods/pragma.js:11:31)\n    at getUserVersion ([REDACTED]/resources/app.asar/preload.bundle.js:2:6586125)\n    at migrateSchemaVersion ([REDACTED]/resources/app.asar/preload.bundle.js:2:6586197)\n    at openAndMigrateDatabase ([REDACTED]/resources/app.asar/preload.bundle.js:2:6587180)\n    at openAndSetUpSQLCipher ([REDACTED]/resources/app.asar/preload.bundle.js:2:6587325)\n    at Object.initializeRenderer ([REDACTED]/resources/app.asar/preload.bundle.js:2:6581177)\n    at Object.initialize ([REDACTED]/resources/app.asar/preload.bundle.js:2:6646481)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async startApp ([REDACTED]/resources/app.asar/preload.bundle.js:2:4402757)"}
{"level":50,"time":"2021-08-31T09:08:14.017Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"SQL failed to initialize SqliteError: file is not a database\n    at Database.pragma ([REDACTED]/resources/app.asar/node_modules/better-sqlite3/lib/methods/pragma.js:11:31)\n    at getUserVersion ([REDACTED]/resources/app.asar/preload.bundle.js:2:6586125)\n    at migrateSchemaVersion ([REDACTED]/resources/app.asar/preload.bundle.js:2:6586197)\n    at openAndMigrateDatabase ([REDACTED]/resources/app.asar/preload.bundle.js:2:6587180)\n    at openAndSetUpSQLCipher ([REDACTED]/resources/app.asar/preload.bundle.js:2:6587325)\n    at Object.initializeRenderer ([REDACTED]/resources/app.asar/preload.bundle.js:2:6581177)\n    at Object.initialize ([REDACTED]/resources/app.asar/preload.bundle.js:2:6646481)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async startApp ([REDACTED]/resources/app.asar/preload.bundle.js:2:4402757)"}
{"level":30,"time":"2021-08-31T09:08:14.018Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"Our profile key service: initializing"}
{"level":30,"time":"2021-08-31T09:08:14.081Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"background page reloaded"}
{"level":30,"time":"2021-08-31T09:08:14.081Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"environment: production"}
{"level":50,"time":"2021-08-31T09:08:14.389Z","pid":86892,"hostname":"bfr.office.bytemine.net","msg":"Top-level unhandled promise rejection: Error: getInstance: globalInstanceRenderer not set!\n    at getInstance ([REDACTED]/resources/app.asar/preload.bundle.js:2:6626314)\n    at getById ([REDACTED]/resources/app.asar/preload.bundle.js:2:6627996)\n    at Object.getItemById ([REDACTED]/resources/app.asar/preload.bundle.js:2:6540735)\n    at Object.getItemById ([REDACTED]/resources/app.asar/preload.bundle.js:2:6531845)\n    at Object.getItemById ([REDACTED]/resources/app.asar/preload.bundle.js:2:6514693)\n    at startApp ([REDACTED]/resources/app.asar/preload.bundle.js:2:4410980)"}
```

Issue persists also after cleaning `~/.config/Signal`

**Comment by bjo81** [comment]
Issue was caused by another build, sorry for the noise.
