### ISSUE TITLE
constant database errors

### ISSUE THREAD

**Issue by damnms** [luminoso/fedora-copr-signal-desktop#13]
i use signal now for about 4 weeks on my workstation, but i had to already destroy/uninstall the complete app because if those wierd errors i sometimes get:

![image](https://user-images.githubusercontent.com/40913090/142722331-fedb8b11-3781-4976-a844-490b27164287.png)
funny tho is also that copy the error does not work, there is nothing in the clipboard.
i must delete everything now again, so i lose all chat history from my workstation because signal does not share this - its a real PITA
```

[oli@fedora ~]$ signal-desktop 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /usr/lib64/signal-desktop/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/oli/.config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
{"level":50,"time":"2021-11-20T10:02:27.737Z","pid":92094,"hostname":"fedora","msg":"MainSQL: SQL corruption: file is not a database in \"PRAGMA journal_mode = WAL\""}
{"level":30,"time":"2021-11-20T10:02:27.737Z","pid":92094,"hostname":"fedora","msg":"MainSQL: migrateDatabase: Migration without cipher change failed"}
{"level":50,"time":"2021-11-20T10:02:27.738Z","pid":92094,"hostname":"fedora","msg":"MainSQL: SQL corruption: statement aborts at 1: [PRAGMA user_version] file is not a database"}
{"level":30,"time":"2021-11-20T10:02:27.739Z","pid":92094,"hostname":"fedora","msg":"app ready"}
{"level":30,"time":"2021-11-20T10:02:27.739Z","pid":92094,"hostname":"fedora","msg":"starting version 5.24.0"}
{"level":30,"time":"2021-11-20T10:02:27.740Z","pid":92094,"hostname":"fedora","msg":"media access status [object Undefined] [object Undefined]"}
{"level":50,"time":"2021-11-20T10:02:27.752Z","pid":92094,"hostname":"fedora","msg":"MainSQL: Database startup error: SqliteError: file is not a database\n    at Database.pragma ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:432:31)\n    at getUserVersion ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:27887:15)\n    at migrateSchemaVersion ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:22613:51)\n    at openAndMigrateDatabase ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:22645:5)\n    at openAndSetUpSQLCipher ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:22661:16)\n    at Object.initialize ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:22698:14)\n    at MessagePort.<anonymous> ([REDACTED].unpacked/ts/sql/mainWorker.bundle.js:25505:36)\n    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)\n    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)"}
{"level":30,"time":"2021-11-20T10:02:27.753Z","pid":92094,"hostname":"fedora","msg":"got fast spellcheck setting true"}
{"level":30,"time":"2021-11-20T10:02:27.753Z","pid":92094,"hostname":"fedora","msg":"getSystemTraySetting had no flags and did no DB lookups. Returning DoNotUseSystemTray"}
{"level":30,"time":"2021-11-20T10:02:27.754Z","pid":92094,"hostname":"fedora","msg":"Initializing BrowserWindow config: {\"show\":false,\"width\":1908,\"height\":954,\"minWidth\":680,\"minHeight\":550,\"autoHideMenuBar\":false,\"titleBarStyle\":\"default\",\"backgroundColor\":\"#3a76f0\",\"webPreferences\":{\"devTools\":false,\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"contextIsolation\":false,\"enableRemoteModule\":true,\"preload\":\"[REDACTED]/preload.bundle.js\",\"nativeWindowOpen\":true,\"spellcheck\":true,\"backgroundThrottling\":false,\"enablePreferredSizeMode\":true},\"icon\":\"[REDACTED]/images/signal-logo-desktop-linux.png\",\"x\":560,\"y\":410}"}
{"level":30,"time":"2021-11-20T10:02:27.799Z","pid":92094,"hostname":"fedora","msg":"spellcheck: user locale: de-DE"}
{"level":30,"time":"2021-11-20T10:02:27.799Z","pid":92094,"hostname":"fedora","msg":"spellcheck: available spellchecker languages:  [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2021-11-20T10:02:27.799Z","pid":92094,"hostname":"fedora","msg":"spellcheck: setting languages to:  [\"de-DE\",\"de\"]"}
{"level":50,"time":"2021-11-20T10:02:27.807Z","pid":92094,"hostname":"fedora","msg":"sql.initialize was unsuccessful; returning early"}
{"level":30,"time":"2021-11-20T10:02:27.808Z","pid":92094,"hostname":"fedora","msg":"close event {\"readyForShutdown\":false,\"shouldQuit\":false}"}
```

**Comment by damnms** [comment]
when i click on "alle daten löschen und neu starten" i get the next error:
![image](https://user-images.githubusercontent.com/40913090/142722441-079991d4-17fa-43f1-b627-d03790f26c59.png)

**Comment by tretkowski** [comment]
Same here, it first started when updating from Fedora 34 to 35 and happens on every update of the Signal Desktop.

**Comment by luminoso** [comment]
I had that once, and didn't happened again. My first thought was because I did a bad shutdown or something.

I'm unsure if this is related to the packaging or the signal-on-fedora itself. It indeed had a sqlite patch in the past but not anymore.

Since I can't reproduce, my suggestion is to leave this ticket open and wait for the next release to see if we can get an idea of what's going on

**Comment by tretkowski** [comment]
Seems like this has nothing to do with your packaging. I tried the binary files from the official Debian package on Fedora 35 and could reproduce the issue when upgrading from 5.23.1 to 5.24.0.

**Comment by luminoso** [comment]
Did anyone got a database error with 5.25.0?

**Comment by damnms** [comment]
worked for me
