### ISSUE TITLE
Signal-Desktop never leaves the "loading" screen with the 3 animated dots when running on CentOS 7

### ISSUE THREAD

**Issue by dtrash1** [luminoso/fedora-copr-signal-desktop#3]
### Bug Description
Signal-Desktop never leaves the "loading" screen with the 3 animated dots when running on CentOS 7.

An error is printed indicating a failure to load glibc 2.18.  CentOS 7 only has glibc 2.17 installed.

### Steps to Reproduce

1.  Starting with (at least v1.34.1) at the bash command line:
```
$ signal-desktop
```
2.  Wait indefinitely at the "loading" screen.

Actual Result:

Signal-Desktop never leaves the "loading" screen with the 3 animated dots.  

Expected Result:

Signal-Desktop starts up normally, loading messages followed by a switch to the messaging UI.

### Screenshots
N/A

### Platform Info

Signal Version:

Reproduced with 1.34.2, 1.34.1

Operating System:

CentOS Linux release 7.8.2003 (Core)

Linked Device Version:

Android: Signal 4.63.3

### Link to Debug Log
The "View"->"Debug Log" menu item is unresponsive, however, the console shows the following:
```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /usr/lib64/signal-desktop/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/REDACTED/.config/Signal
config/get: Successfully read user config file
x-attr dependncy did not load successfully
config/get: Successfully read ephemeral config file
making app single instance
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"app ready","time":"2020-06-18T00:35:32.239Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"starting version 1.34.2","time":"2020-06-18T00:35:32.239Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"updateSchema:\n  Current user_version: 20;\n  Most recent db schema: 20;\n  SQLite version: 3.30.1;\n  SQLCipher version: 4.3.0 community;\n  (deprecated) schema_version: 60;\n","time":"2020-06-18T00:35:32.248Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"Initializing BrowserWindow config: {\"show\":true,\"width\":938,\"height\":822,\"minWidth\":680,\"minHeight\":550,\"autoHideMenuBar\":false,\"backgroundColor\":\"#3a76f0\",\"webPreferences\":{\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"contextIsolation\":false,\"preload\":\"/usr/lib64/signal-desktop/resources/app.asar/preload.js\",\"nativeWindowOpen\":true,\"spellcheck\":true},\"icon\":\"/usr/lib64/signal-desktop/resources/app.asar/images/signal-logo-desktop-linux.png\",\"x\":3392,\"y\":301}","time":"2020-06-18T00:35:32.269Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"spellcheck: user locale: en-US","time":"2020-06-18T00:35:32.364Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"spellcheck: available spellchecker languages:  [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"el\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]","time":"2020-06-18T00:35:32.364Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"spellcheck: setting languages to:  [\"en-US\"]","time":"2020-06-18T00:35:32.364Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"Begin ensuring permissions","time":"2020-06-18T00:35:32.380Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"Ensuring file permissions for 2 files","time":"2020-06-18T00:35:32.392Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"Finish ensuring permissions in 13ms","time":"2020-06-18T00:35:32.393Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"msg":"Preload error in [REDACTED]/app.asar/preload.js:  Dynamic Linking Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by [REDACTED]/app.asar.unpacked/node_modules/zkgroup/libzkgroup.so)","time":"2020-06-18T00:35:32.856Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"Updating BrowserWindow config: {\"maximized\":false,\"autoHideMenuBar\":false,\"fullscreen\":false,\"width\":938,\"height\":822,\"x\":3392,\"y\":338}","time":"2020-06-18T00:35:32.885Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"msg":"config/set: Saving ephemeral config to disk","time":"2020-06-18T00:35:32.885Z","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":30,"time":"2020-06-18T00:35:33.078Z","msg":"pre-main prep time: 2 ms","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.124Z","msg":"Top-level unhandled error: TypeError: Cannot read property 'Util' of undefined\n    at new SignalProtocolStore (file://[REDACTED]/app.asar/js/signal_protocol_store.js:169:47)\n    at file://[REDACTED]/app.asar/js/libtextsecure.js:36624:33\n    at file://[REDACTED]/app.asar/js/libtextsecure.js:36629:3\n    at file://[REDACTED]/app.asar/js/libtextsecure.js:36789:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.128Z","msg":"Top-level unhandled error: ReferenceError: Signal is not defined\n    at file://[REDACTED]/app.asar/js/notifications.js:16:24\n    at file://[REDACTED]/app.asar/js/notifications.js:211:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.133Z","msg":"Top-level unhandled error: ReferenceError: Signal is not defined\n    at file://[REDACTED]/app.asar/js/models/messages.js:23:67\n    at file://[REDACTED]/app.asar/js/models/messages.js:2656:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.137Z","msg":"Top-level unhandled error: TypeError: Cannot destructure property 'Util' of 'window.Signal' as it is undefined.\n    at file://[REDACTED]/app.asar/js/models/conversations.js:29:11\n    at file://[REDACTED]/app.asar/js/models/conversations.js:2615:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.140Z","msg":"Top-level unhandled error: TypeError: Whisper.ConversationCollection is not a constructor\n    at file://[REDACTED]/app.asar/js/conversation_controller.js:13:25\n    at file://[REDACTED]/app.asar/js/conversation_controller.js:265:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.148Z","msg":"Top-level unhandled error: TypeError: Cannot read property 'Types' of undefined\n    at file://[REDACTED]/app.asar/js/views/conversation_view.js:20:61\n    at file://[REDACTED]/app.asar/js/views/conversation_view.js:3141:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.148Z","msg":"Top-level unhandled error: ReferenceError: i18n is not defined\n    at file://[REDACTED]/app.asar/js/views/inbox_view.js:71:16\n    at file://[REDACTED]/app.asar/js/views/inbox_view.js:207:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.150Z","msg":"Top-level unhandled error: TypeError: Cannot destructure property 'Logs' of 'window.Signal' as it is undefined.\n    at file://[REDACTED]/app.asar/js/views/clear_data_view.js:11:11\n    at file://[REDACTED]/app.asar/js/views/clear_data_view.js:67:3","v":0}
{"name":"log","hostname":"REDACTED","pid":8229,"level":50,"time":"2020-06-18T00:35:33.158Z","msg":"Top-level unhandled promise rejection: TypeError: Cannot read property 'Util' of undefined","v":0}
```

**Comment by dtrash1** [comment]
Downgrading to `signal-desktop.x86_64 0:1.33.4-1.el7` works as expected.

**Comment by luminoso** [comment]
Thank you for testing. I'm going to try to reproduce the issue. 

I anticipate that this may be a upstream problem, since there's close to no difference between 1.33.4 and 1.34.2 spec file :thinking:

**Comment by luminoso** [comment]
Oh boy.. Signal [included yet another binary](https://github.com/signalapp/Signal-Desktop/blob/419f219f916619ac9292863e5049970a80390dd4/package.json#L262) in their release and it looks like it is the source of the problem.

The library is built against `GLIBC_2.18` while el7 has `GLIBC_2.17`

To solve it looks like that `libzkgroup.so` from [signal-zkgroup-node](https://github.com/signalapp/signal-zkgroup-node) must be rebuilt. hum.

Thankfully, other people are facing the [same issue](https://github.com/signalapp/Signal-Desktop/issues/3410) 

I'll try to do this. If you have any other idea let me know

**Comment by luminoso** [comment]
Ok just made a new build. c6a1530 should fix the issue.

Can you please update your system to see if the fix also works for you?

**Comment by dtrash1** [comment]
The latest build completely solves the issue on my configuration.  Thanks!
